### ISSUE TITLE
Impossible to define mock for object fields?

### ISSUE THREAD

**Issue by rexxars** [EasyGraphQL/easygraphql-mock#30]
Let's imagine the following schema:

```graphql
type Image {
  url: String
}

type Author {
  name: String
  image: Image
}

# ... other types here 
```

If you wanted to explicitly define the mock value for `Author`, you would pass say:
```js
const ImageMock = {
  url: 'https://foo.bar/img.jpg'
}

const AuthorMock = {
  name: 'Espen',
  image: ImageMock
}

easyGraphqlMock(sdl, {
  Author: AuthorMock,
  Image: ImageMock
}
```

Which results in:
```
Error: Field name IMAGE type is different on the Schema
    at getCustomMockData (/easygraphql-mock/util/customMock.js:66:11)
    at createData (/easygraphql-mock/util/index.js:64:12)
    at schema.(anonymous function).fields.forEach.field (/easygraphql-mock/util/index.js:37:20)
    at Array.forEach (<anonymous>)
    at mockedField (/easygraphql-mock/util/index.js:36:25)
    at /easygraphql-mock/util/index.js:23:20
    at createData (/easygraphql-mock/util/index.js:127:16)
    at schema.(anonymous function).fields.forEach.field (/easygraphql-mock/util/index.js:37:20)
    at Array.forEach (<anonymous>)
    at mockedField (/easygraphql-mock/util/index.js:36:25)
    at /easygraphql-mock/util/index.js:23:20
    at mockBuilder (/easygraphql-mock/lib/mockBuilder.js:15:23)
```

The check in question seems to be incomplete - it returns string/number for those types, but undefined for everything else, making it impossible to actually make it pass.

**Comment by estrada9166** [comment]
@rexxars Thanks for creating this issue!! This actually something to improve!

At this moment it works like this:
```js
const ImageMock = {
  url: 'https://foo.bar/img.jpg'
}

const AuthorMock = {
  name: 'Espen',
  Image: ImageMock
}

const mock = easygqlmock(schema, {
  Author: AuthorMock,
  Image: ImageMock
})
```
As you can see the nested field is another `type`, so, that's why it should be set like this (`Image`):
```js
const AuthorMock = {
  name: 'Espen',
  Image: ImageMock
}
```
insted of (`image)`:
```js
const AuthorMock = {
  name: 'Espen',
  image: ImageMock
}

**Comment by rexxars** [comment]
Huh.. make the field name capitalized?

**Comment by estrada9166** [comment]
Sorry about the vague explanation, in this case, it works like this because you set the type on the mock:
```
const mock = easygqlmock(schema, {
  Author: AuthorMock,
  Image: ImageMock
})
```
but it'll not set them if you use it like this:
```js
const ImageMock = {
  url: 'https://foo.bar/img.jpg'
}

const AuthorMock = {
  name: 'Espen',
  Image: ImageMock
}

const mock = easygqlmock(schema, {
  Author: AuthorMock
})
```
It'll set the value to the type and those values will be set to the nested field.

**Comment by rexxars** [comment]
I think I get it. I worked my way around it for the time being, so not really an issue anymore - I'll leave it for you to decide whether it's something you want to document/fix/make easier :)
